[project]
name = "Aimbot"
version = "0.0"
authors = [{ name = "EdricY" }]
description = """\
Auto aim and track enemy crit points. It's an aimbot.
"""

[project.urls]
Source = "https://github.com/EdricY/EdricY-BL2-sdk-mods/tree/main/AimBot"

[tool.sdkmod]
name = "Aimbot"
license = {name = "MIT", url = "https://choosealicense.com/licenses/mit/" }
download = "https://github.com/EdricY/EdricY-BL2-sdk-mods/blob/main/AimBot/AimBot.sdkmod"